### ISSUE TITLE
Custom layout doesn't exist: custom:layout-card

### ISSUE THREAD

**Issue by meijieru** [folke/lovelace-styler#25]
When I try the example from the readme, I encountered the above error.
I installed the addon through HACS, the version is v1.4.1

**Comment by folke** [comment]
I just pushed a bunch of updates and updated the example for the room cards.
The error you encountered is because the example needed the lovelace-layout plugin.

The new example on the README no longer has that dependency and is now much much shorter code wise.

**Comment by meijieru** [comment]
Thanks, the example works!
However, I'm encountering an issue where Tile Card Customization seems to be malfunctioning in v3.0 – the intended information isn't being hidden.
Here's my code for reference:

```yaml
type: horizontal-stack
layout_options:
  grid_columns: 2
styler:
  card: true
cards:
  - type: custom:mushroom-template-card
    primary: Bedroom
    secondary: '{{ states(''sensor.temperature_sensor_2'') | round(0) }} °C'
    icon: mdi:bed
    icon_color: blue
    tap_action:
      action: navigate
      navigation_path: downstairs
    styler:
      style: |
        mushroom-state-info { min-height: 150px }
        ha-card { --icon-size: 130px }
        mushroom-shape-icon {
          position: absolute;
          margin: -20px -25px;
        }
  - type: grid
    columns: 1
    square: false
    styler:
      style: |
        :host {
          flex: 0 0 auto !important;
          margin: 12px;
        }
    cards:
      - type: tile
        info: false
        entity: light.bedroom_light
```
